Repository InessaRepeshko/ucode-endgame, pull requests merged in 2023-02, with the labels that each got.

#5 Update README.md; Update jump
  README.md
  src/main.c
Labels: enhancement

#7 platforms
  Makefile
  inc/main.h
  src/main.c
Labels: enhancement

#8 [add-double-jump] Add double jump
  .gitignore
  src/main.c
Labels: enhancement

#9 [add-lava] Add lava as enemy and bug fix
  README.md
  src/main.c
Labels: enhancement

#10 platforms
  src/main.c
Labels: enhancement

#11 [add-events] Add events
  inc/main.h
  src/camera.c
  src/main.c
Labels: bug, enhancement

#12 [add-animation] Add animation
  scarfy.png
  src/main.c
Labels: enhancement

#14 Lava of the highest quality
  resources/textures/lava.gif
  src/main.c
Labels: enhancement

#15 [add-character-animation] Add character animation
  inc/main.h
  resources/textures/character_1.png
  resources/textures/character_2.png
  scarfy.png
  src/main.c
Labels: enhancement

#16 sides and platform textures
  inc/main.h
  resources/textures/back.png
  resources/textures/board.png
  resources/textures/dynamic.png
  resources/textures/flour.png
  resources/textures/pyramid.png
  resources/textures/static.png
  src/main.c
Labels: enhancement

#17 [main] Fix merge conflict
  inc/main.h
  src/main.c
Labels: bug

#18 [refactoring] Add lava structure
  inc/main.h
  src/main.c
Labels: good first issue

#19 [refactoring] Update lava structure
  inc/main.h
  src/main.c
Labels: good first issue

#20 [refactoring] Update Player struct
  inc/main.h
  src/main.c
Labels: good first issue

#21 [refactoring] Update physics and rename textures
  src/main.c
Labels: good first issue

#23 add music, buttoms and some textures
  inc/main.h
  resources/textures/almaz.png
  resources/textures/flag.png
  resources/textures/lava.gif
  resources/textures/lava/lava.gif
  resources/textures/lava/lava1.gif
  resources/textures/lava/lava2.gif
  resources/textures/stand.png
  src/main.c
Labels: enhancement

#24 Update logic music
  src/main.c
Labels: bug, enhancement

#25 [feature] Add level design and textures.
  resources/textures/back.png
  resources/textures/block_crashing1.png
  resources/textures/block_crashing2.png
  resources/textures/block_moving.png
  resources/textures/block_static.png
  resources/textures/board.png
  resources/textures/dynamic.png
  resources/textures/flour.png
  resources/textures/pyramid.png
  resources/textures/static.png
  resources/textures/wall_background.png
  resources/textures/wall_bottom.png
  resources/textures/wall_left.png
  resources/textures/wall_level_top.png
  resources/textures/wall_right.png
  src/main.c
Labels: enhancement

#26 [feature] Update move set and fix almaz bug
  resources/textures/buttons/move_set.png
  src/main.c
Labels: bug, enhancement

#27 [bug-fix] Fix physic bug
  inc/main.h
  src/main.c
Labels: bug
